In [1]:
import numpy as np
arr = np.array([[1,0,2,3],[4,6,3,8],[9,7,8,9],[4,8,1,0]])
print(arr)

[[1 0 2 3]
 [4 6 3 8]
 [9 7 8 9]
 [4 8 1 0]]


In [2]:
print(arr[0:3:2])

[[1 0 2 3]
 [9 7 8 9]]


In [3]:
temp = arr[:2,:3]
print(temp)

[[1 0 2]
 [4 6 3]]


In [4]:
temp = arr[[0,1,3,2],[1,3,2,1]]
print(temp)

[0 8 1 7]


In [5]:
cond = arr>2
temp = arr[cond]
print(temp)

[3 4 6 3 8 9 7 8 9 4 8]


In [6]:
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr[::2])

[1 2 3 4 5 6 7]
[1 3 5 7]


In [7]:
arr1 = np.array([1,3,5])
arr2 = np.array([2,4,6])
arr = np.concatenate((arr1,arr2))
print(arr1,arr2)
print(arr)

[1 3 5] [2 4 6]
[1 3 5 2 4 6]


In [9]:
arr = np.hstack((arr1,arr2))
print(arr)

[1 3 5 2 4 6]


In [11]:
arr = np.vstack((arr1,arr2))
print(arr)

[[1 3 5]
 [2 4 6]]


In [12]:
arr = np.dstack((arr1,arr2))
print(arr)

[[[1 2]
  [3 4]
  [5 6]]]


In [13]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,2)
print(arr)
print(newarr)

[1 2 3 4 5 6]
[array([1, 2, 3]), array([4, 5, 6])]


In [14]:
print(newarr[0])
print(newarr[1])

[1 2 3]
[4 5 6]
