In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,5,5])
print(arr)
x = np.where(arr==5)
print(x)

[1 2 3 4 5 5 5]
(array([4, 5, 6], dtype=int64),)


In [3]:
arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr%2==0)
print(arr)
print(x)

[1 2 3 4 5 6 7 8]
(array([1, 3, 5, 7], dtype=int64),)


In [4]:
x = np.searchsorted(arr,3,side='left')
print(x)

2


In [6]:
arr = np.array([3,2,0,1])
print(arr)
print(np.sort(arr))

[3 2 0 1]
[0 1 2 3]


In [7]:
arr = np.array([41,42,43,44])
x = [True,False,True,False]
newarr = arr[x]
print(arr)
print(x)
print(newarr)

[41 42 43 44]
[True, False, True, False]
[41 43]


In [9]:
arr = np.array([41,42,43,44])
filter_arr = arr>41
newarr = arr[filter_arr]
print(arr)
print(filter_arr)
print(newarr)

[41 42 43 44]
[False  True  True  True]
[42 43 44]
