In [1]:
import numpy as np
arr1 = [10,20,30,40,50]
arr2 = [2,4,5,8,10]
a = np.array(arr1)
b = np.array(arr2)
print(a)
print(b)

[10 20 30 40 50]
[ 2  4  5  8 10]


In [2]:
print(a+b)

[12 24 35 48 60]


In [3]:
print(a-b)

[ 8 16 25 32 40]


In [4]:
print(a*b)

[ 20  80 150 320 500]


In [5]:
print(a/b)

[5. 5. 6. 5. 5.]


In [6]:
print(a.dot(b))

1070


In [7]:
sclr = 5
print(sclr)

5


In [8]:
print(a)
print(a*sclr)

[10 20 30 40 50]
[ 50 100 150 200 250]
