In [1]:
import numpy as np
a = np.array([[1,2,4],[5,8,7]])
print(a)

[[1 2 4]
 [5 8 7]]


In [2]:
b = np.zeros((3,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
c = np.full((3,3),6)
print(c)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [5]:
d = np.random.random((2,2))
print(d)


[[0.84364504 0.87159957]
 [0.83700598 0.33073437]]


In [7]:
e = np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]


In [8]:
arr = np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr = arr.reshape(4,3)
print(arr)
print(newarr)

[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
[[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [9]:
f = arr.flatten()
print(arr)
print(f)

[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
[1 2 3 4 5 2 4 2 1 2 0 1]


In [10]:
print(arr.ndim)

2


In [11]:
print(arr.shape)

(3, 4)


In [12]:
print(arr.size)

12


In [13]:
print(arr.dtype)

int32


In [15]:
newtype = arr.astype('f')
print(newtype)
print(newtype.dtype)

[[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
float32
